apiVersion: v1
kind: ConfigMap
metadata:
  name: my-plugin-config
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: my-plugin
    spec:
      init:
        command: [sh, -c, 'echo "Initializing..."']
      generate:
        command:
          - sh
          - -c
          - |
            output_file="generated_manifestwork"
            echo "apiVersion: work.open-cluster-management.io/v1" > $output_file
            echo "kind: ManifestWork" >> $output_file
            echo "metadata:" >> $output_file
            echo "  name: ${ARGOCD_APP_NAME}" >> $output_file
            echo "  namespace: ${ARGOCD_ENV_TARGET_CLUSTER}" >> $output_file
            echo "spec:" >> $output_file
            echo "  workload:" >> $output_file
            echo "    manifests:" >> $output_file
            for file in $(find . -name "*.yaml"); do
              if [ -s $file ]; then
                echo "    -" >> $output_file
                cat $file | sed 's/^/      /' >> $output_file
              fi
            done
            cat $output_file
